spring:
  application:
    name: db-service
  datasource:
    password: admin
    testWhileIdle: true
    url: jdbc:mysql://192.168.99.100:3306/mf-feeder-service-test?verifyServerCertificate=false&useSSL=true
    username: admin
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  security:
    user:
      name: client
      password: client
  jackson:
    serialization:
      indent_output: true
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        password: admin
        url: http://localhost:8305/admin
        username: admin

server:
  port: 8303

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck :
      enabled : true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
    lease:
      duration: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  level:
#    root: debug