spring:
  application:
    name: finance-eureka-server
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        password: admin
        url: http://localhost:8305/admin
        username: admin
  security:
    user:
      name: client
      password: client

server:
  port: 8301

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0

#logging:
#  level:
#    root: debug